# Numpy Basics
#### My Personal notes on Numpy Module



1. Import Numpy Module

In [ ]:
import numpy as np

2. Call `np.array` to create a Numpy Matrix

In [ ]:
array1 = np.array([34.2, 2.4, 45.3, 19.1, 12.3, 4.4]) # one Dimensional array
print(array1)

array2 = np.array([[3, 43], [12, 65], [33, 4]]) # two dimensional array
print(array2)

[34.2  2.4 45.3 19.1 12.3  4.4]
[[ 3 43]
 [12 65]
 [33  4]]


3. `np.zeroes` = matrix with all zeroes
4. `np.ones` = matrix with all ones

In [ ]:
aZeros = np.zeros(5)
print(aZeros)

bOnes = np.ones(6)
print(bOnes)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


5. `np.arrange` = generates no. sequence, including lower but excluding upper limit.

In [ ]:
numbers_count = np.arange(7, 20)
print(numbers_count)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]


6. `np.random.randint`: generate random nos between set range (highest generated will be one less than the high limit)

7. `np.random.random`: generate random floating point between 0.0 and 1.0


In [ ]:
random_int_btw_30_and_100 = np.random.randint(low=30, high=101, size=(6))
print(random_int_btw_30_and_100 )

random_floats_btw_0_and_1 = np.random.random([6])
print(random_floats_btw_0_and_1) 

[78 71 87 93 40 74]
[0.15857045 0.34602089 0.97423831 0.68462745 0.58427409 0.13374366]


8. NumPy uses **broadcasting** to virtually expand the smaller operand to dimensions compatible for linear algebra.

In [ ]:
#add 3.0 to the value of every item in the vector created in the previous code cell

random_floats_between_3_and_4 = random_floats_btw_0_and_1 + 3.0
print(random_floats_between_3_and_4)

[3.15857045 3.34602089 3.97423831 3.68462745 3.58427409 3.13374366]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [ ]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created.

In [ ]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)

[ 1.02968275 -1.33505263  1.76207814 -0.85854424  0.52142086 -1.54388363
  1.89154727  0.05585134  1.7093753  -1.91015302  0.9581475  -1.97003717
 -1.33264323 -0.0353665  -0.7186342 ]
[23.02968275 23.66494737 29.76207814 30.14145576 34.52142086 35.45611637
 41.89154727 43.05585134 47.7093753  47.08984698 52.9581475  53.02996283
 56.66735677 60.9646335  63.2813658 ]
